//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach3._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int ID_Goods { get; set; }
        public string Title_Goods { get; set; }
        public Nullable<int> Vendore_code_goods { get; set; }
        public Nullable<int> Prime_cost_goods { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Sold { get; set; }
        public Nullable<int> Decommisioned { get; set; }
        public Nullable<int> In_Stock { get; set; }
        public Nullable<int> ID_Category { get; set; }
        public Nullable<int> ID_supplier { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
